name: CI
on:
  repository_dispatch:
    types: build-and-release


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.branch }}
    - name: Run a one-line script
      run: echo ${{ github.event.client_payload.text }}
